export default {
  admin: [
    {
      name: "Home",
      url: "/dashboard",
      icon: "el-icon-platform-eleme",
      color_icon: "#f9b651",
    },

    {
      name: "Câu hỏi",
      url: "/question",
      icon: "el-icon-question",
      color_icon: "#ff4d4d",
    },
    {
      name: "Quản trị câu hỏi / Trả lời",
      url: "/question/questionTables",
      icon: "el-icon-s-grid",
      color_icon: "#f9b651",
    },
    {
      name: "Quản trị tài liệu / Bài đăng",
      url: "/post/postTables",
      icon: "el-icon-menu",
      color_icon: "#ca2c2a",
    },
    {
      name: "Quản lý người dùng",
      url: "/user",
      icon: "el-icon-user-solid",
      color_icon: "#84e8c8",
    },
    {
      name: "Quản trị thông tin sinh viên",
      url: "/student",
      icon: "el-icon-user",
      color_icon: "#84e8c8",
    },
    {
      name: "Quản trị thông tin cố vấn",
      url: "/consultant",
      icon: "el-icon-s-custom",
      color_icon: "#84e8c8",
    },
    {
      name: "Điểm rèn luyện",
      url: "/training_point",
      icon: "el-icon-reading",
      color_icon: "#0000FF",
    },
    {
      name: "Quản trị điểm rèn luyện",
      url: "/training_point/detailTrainingPoint",
      icon: "el-icon-tickets",
      color_icon: "#0000FF",
    },
    {
      name: "Kết quả rèn luyện",
      url: "/training_point/resultTraningPoint",
      icon: "el-icon-notebook-2",
      color_icon: "#0000FF",
    },
    {
      name: "Tra cứu thông tin",
      url: "/note_book",
      icon: "el-icon-search",
      color_icon: "#FF6600	",
    },
    {
      name: "",
      url: "",
      icon: "el-icon-loading",
      color_icon: "#00EE00",
    },
  ],
  student: [
    {
      name: "Home",
      url: "/dashboard",
      icon: "el-icon-platform-eleme",
      color_icon: "#f9b651",
    },

    {
      name: "Câu hỏi",
      url: "/question",
      icon: "el-icon-question",
      color_icon: "#ff4d4d",
    },
    {
      name: "Quản trị câu hỏi / Trả lời",
      url: "/question/questionTables",
      icon: "el-icon-s-grid",
      color_icon: "#f9b651",
    },
    {
      name: "Quản trị tài liệu / Bài đăng",
      url: "/post/postTables",
      icon: "el-icon-menu",
      color_icon: "#ca2c2a",
    },
    {
      name: "Quản lý người dùng",
      url: "/user",
      icon: "el-icon-user-solid",
      color_icon: "#84e8c8",
    },
    {
      name: "Quản trị thông tin sinh viên",
      url: "/student",
      icon: "el-icon-user",
      color_icon: "#84e8c8",
    },
    {
      name: "Quản trị thông tin cố vấn",
      url: "/consultant",
      icon: "el-icon-s-custom",
      color_icon: "#84e8c8",
    },
    {
      name: "Điểm rèn luyện",
      url: "/training_point",
      icon: "el-icon-reading",
      color_icon: "#0000FF",
    },
    {
      name: "Quản trị điểm rèn luyện",
      url: "/training_point/detailTrainingPoint",
      icon: "el-icon-tickets",
      color_icon: "#0000FF",
    },
    {
      name: "Kết quả rèn luyện",
      url: "/training_point/resultTraningPoint",
      icon: "el-icon-notebook-2",
      color_icon: "#0000FF",
    },
    {
      name: "Tra cứu thông tin",
      url: "/note_book",
      icon: "el-icon-search",
      color_icon: "#FF6600	",
    },
    {
      name: "Cài đặt",
      url: "/setting",
      icon: "el-icon-s-tools",
      color_icon: "#010101",
    },
    {
      name: "",
      url: "",
      icon: "el-icon-loading",
      color_icon: "#00EE00",
    },
  ],
  consultant: [
    {
      name: "Home",
      url: "/dashboard",
      icon: "el-icon-platform-eleme",
      color_icon: "#f9b651",
    },

    {
      name: "Câu hỏi",
      url: "/question",
      icon: "el-icon-question",
      color_icon: "#ff4d4d",
    },
    {
      name: "Quản lý người dùng",
      url: "/user",
      icon: "el-icon-user-solid",
      color_icon: "#84e8c8",
    },
    {
      name: "Quản trị thông tin sinh viên",
      url: "/student",
      icon: "el-icon-user",
      color_icon: "#84e8c8",
    },
    {
      name: "Quản trị thông tin cố vấn",
      url: "/consultant",
      icon: "el-icon-s-custom",
      color_icon: "#84e8c8",
    },
    {
      name: "Quản trị câu hỏi / Trả lời",
      url: "/question/questionTables",
      icon: "el-icon-s-grid",
      color_icon: "#f9b651",
    },
    {
      name: "Quản trị tài liệu / Bài đăng",
      url: "/post/postTables",
      icon: "el-icon-menu",
      color_icon: "#ca2c2a",
    },
    {
      name: "Điểm rèn luyện",
      url: "/training_point",
      icon: "el-icon-reading",
      color_icon: "#0000FF",
    },
    {
      name: "Quản trị điểm rèn luyện",
      url: "/training_point/detailTrainingPoint",
      icon: "el-icon-tickets",
      color_icon: "#0000FF",
    },
    {
      name: "Kết quả rèn luyện",
      url: "/training_point/resultTraningPoint",
      icon: "el-icon-notebook-2",
      color_icon: "#0000FF",
    },
    {
      name: "Tra cứu thông tin",
      url: "/note_book",
      icon: "el-icon-search",
      color_icon: "#FF6600	",
    },
    {
      name: "Cài đặt",
      url: "/setting",
      icon: "el-icon-s-tools",
      color_icon: "#010101",
    },
    {
      name: "",
      url: "",
      icon: "el-icon-loading",
      color_icon: "#00EE00",
    },
  ],
};

